name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: checks
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Copy modules into dist
      run: cp -r node_modules fpb-dist/node_modules

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "fpb-dist/"
        REMOTE_HOST: ${{ secrets.EC2_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.EC2_REMOTE_USER }}
        TARGET: "fpb-dist"
