name: Experiment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo github context
        run: echo ${{ github }}
        